name: global_multiple_snapheights_modalbottomsheet
description: ModalBottomSheet that support multiple snapHeights, overlay widget in all pages.
version: 2.0.0
homepage: https://github.com/nhh1500/Global-multiple-snapPoints-modalbottomsheet

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
